@startuml

actor "Alice"
actor "Bob"

"Bob" <[#lightgrey]- "Alice": Sendet BT-MAC-Adresse per WiFi-Direct
"Alice" <[#lightgrey]- "Bob": Sendet BT-MAC-Adresse per WiFi-Direct
"Alice" <[#lightgrey]- "Alice": Abfrage des Radars
"Bob" <[#lightgrey]- "Alice": Sendet Broadcast-Nachricht per BT
"Bob" <- "Bob": **Sequenznummerüberprüfung**
"Bob" <[#lightgrey]- "Bob": Filterüberprüfung

@enduml