@startuml

actor "Alice"
actor "Bob"

"Bob" <[#lightgrey]- "Alice": Sendet BT-Mac-Adresse per WiFi-Direct
"Alice" <[#lightgrey]- "Bob": Sendet BT-Mac-Adresse per WiFi-Direct
"Alice" <[#lightgrey]- "Alice": Abfrage des Radars
"Bob" <[#lightgrey]- "Alice": Sendet Broadcast-Nachricht per BT
"Bob" <[#lightgrey]- "Bob": Sequenznummerüberprüfung
"Bob" <- "Bob": Filterüberprüfung

@enduml