@startuml
actor "Alice"

box #lightblue
    participant SharkServer
    participant ASIPSession
	actor "Bob"
end box


Alice -> SharkServer: Aufbau StreamConnection
SharkServer -> ASIPSession: Aufbau einer Session
activate ASIPSession
ASIPSession -> ASIPSession: Erzeugung ASIPInMessage
ASIPSession -> ASIPSession: Nachricht wird vom Stream gelesen
ASIPSession --> Alice: StreamConnnection wird geschlossen
deactivate ASIPSession
ASIPSession -> Bob: Aufruf handleMessage()

@enduml